### alcohol의 댓글 작성 - 성공
POST http://localhost:8080/alcohol/1/comments
Content-Type: application/json

{
  "content": "이 술 맛있습니다"
}

### alcohol의 댓글 작성 - 실패
POST http://localhost:8080/alcohol/1/comments
Content-Type: application/json

{
  "content": ""
}